### ISSUE TITLE
null == null?

### ISSUE THREAD

**Issue by sagotch** [tategakibunko/jingoo#101]
```ocaml
let rec jg_eq_eq_aux left right =
  match left, right with
    | Tint x1, Tint x2 -> x1=x2
    | Tfloat x1, Tfloat x2 -> x1=x2
    | Tstr x1, Tstr x2 -> x1=x2
    | Tbool x1, Tbool x2 -> x1=x2
    | Tlist x1, Tlist x2
    | Tset x1, Tset x2 -> jg_list_eq_eq x1 x2
    | Tarray x1, Tarray x2 -> jg_array_eq_eq x1 x2
    | Tobj _, Tobj _ ->
      begin
        try unbox_bool @@ jg_apply (jg_obj_lookup left "__eq__") [ left ; right ]
        with _ -> jg_obj_eq_eq left right
      end
    | ((Thash _ | Tobj _ | Tpat _) as left), ((Thash _ | Tobj _ | Tpat _) as right) ->
      begin
        try unbox_bool @@ jg_apply (jg_obj_lookup left "__eq__") [ left ; right ]
        with _ -> false
      end
    | _, _ -> false
```

With the current behavior, it is impossible to write a test such as `{% if x == null %}`. It seems counter-intuitive. It is particularly true when trying to handle `{% case null %}`, which is not possible.

Is there a reason why `null != null`? If so, we should document this. If not, do we change the behavior?

Another way to solve this is to specialize the test perform when it is with `LiteralExpr Tnull`. I would actually prefer this. But I have no strong opinion on this, so if you prefer to simplify things `jg_eq_eq_aux Tnull Tnull = true` would solve the issue as well.

**Comment by tategakibunko** [comment]
I simply forgot to compare null in pattern match... apparently this is a bug. Thank you for your feedback.

As you pointed out,

```ocaml
match left, right with
| Tnull, Tnull -> true
```
would solve this issue simply for now.

**Comment by tategakibunko** [comment]
Fixed by simple solution.

https://github.com/tategakibunko/jingoo/commit/6376b16202408ae4aa96586ace0c7394077fe860
