### ISSUE TITLE
In Jingoo.Jg_template, provide a function for the getting variables

### ISSUE THREAD

**Issue by Chimrod** [tategakibunko/jingoo#112]
In Jingoo.Jg_template, each function take an association list for defining the values. Is it possible to have this on : ?⁠models:(string -> Jg_types.tvalue)

This allow to use different sources for the variables.

**Comment by sagotch** [comment]
I'd like to use this as well, but I did not have time to work on a PR to allow this (yet).

**Comment by Chimrod** [comment]
The change is pretty straigtforward, but break the actual API. Before sending a PR, I would like to know how to implement this change : 

- create new functions in parallel with the existing ones
- replace the actual signature and break all the code which rely on this ?

This decision has to be taken by the project before considering any change…

**Comment by tategakibunko** [comment]
Hmm, `string ->	tvalue`	is model getter	instead	of assoc list?

But new function for this feature may confuse the users.

What I thought about this feature is adding new keyword argument like `model_getter` which is set to `None` by default (I want keep `models` to assoc list for backward compatibility).

It would break signature but old code works.

But if we have different kind of source for models, then we have to prioritize the variables, assoc list first, or getter first...

```ocaml
let getter_models key =
  match key with
  | "name" -> Tstr "foo"
  | _ -> Tnull

let assoc_models = [("name", Tstr "bar")]

(* 'foo' or 'bar'? *)
Jg_template.from_string	"{{ name }}"
 ~models:assoc_models
 ~model_getter:(Some getter_models)
```

I'd like to know the signature of the function you're trying to implement.

**Comment by Chimrod** [comment]
I think that mixing two behavor in the same function is more confusing.

In internal, you will not have to keep the Hastbl in the [model_frame](https://github.com/tategakibunko/jingoo/blob/master/src/jg_runtime.ml#L1554) and the signature for the differents parser would just change :

[Jg_interp.from_file](https://github.com/tategakibunko/jingoo/blob/09f7031b5b14e3c70d09e66877888e23ad4293f5/src/jg_interp.ml#L470) will get this implemation which keep the same signature :

```ocaml
let from_file
    ?(env=std_env) ?(models=[]) ~output
    ?(ctx = init_context ~env ~(models=(fun x -> List.assoc models x)) ~output ())
    file_name =
  Loaded.eval (Loaded.from_file ~env file_name) ~output ~ctx ()
```

(and would be derived for the differents constructors)

I'm in favor to adding parallels function and conserving the existing API

**Comment by tategakibunko** [comment]
Oh I see!

Does it changes **internal** signature(like `init_context`), but keeps outside signature(like `from_file`) same?

Then it's OK for me.

**Comment by tategakibunko** [comment]
And you want to add parallel new API which use functional models, is it right?

**Comment by Chimrod** [comment]
I've just pushed a [commit](https://github.com/Chimrod/jingoo/commit/f0432b5cc10cc32fdd9916c77a897130fd58ea7c) with all the requirements for the evolution.

Some notables changes : 

- The type [frame](https://github.com/Chimrod/jingoo/blob/model_template/src/jg_types.mli#L53) accept both hashtabl (like before) and functions. It is represented with a sum type.
- [jg_push_frame](https://github.com/tategakibunko/jingoo/blob/master/src/jg_runtime.ml#L56) now create a [closure](https://github.com/Chimrod/jingoo/blob/model_template/src/jg_runtime.ml#L56) instead of modifying the context directly.

The tests are Ok (except file inclusion because I'm on a Windows system). Feel free to review the code, then evaluate if I should go further.

**Comment by sagotch** [comment]
I do not understand the point of `Custom _  | Internal t`.

`Internal t` is just `Custom (Hashtbl.find t)` isn't ?

**Comment by sagotch** [comment]
Ok, so this is where you introduce the need for `Internal`

```
    begin match Hashtbl.find ctx.namespace_table ns with
    | Custom _ -> ()
    | Internal m -> Hashtbl.add m v (value_of_expr env ctx expr)
    end;
```

**Comment by sagotch** [comment]
Also, `namespace_table` should probably become

```
namespace_table : (string, (string, tvalue) Hashtbl.t) Hashtbl.t;
```

So we can revert

```
-    Hashtbl.add
-      (Hashtbl.find ctx.namespace_table ns) v (value_of_expr env ctx expr) ;
+    begin match Hashtbl.find ctx.namespace_table ns with
+    | Custom _ -> ()
+    | Internal m -> Hashtbl.add m v (value_of_expr env ctx expr)
+    end;
```
and
```
-    Hashtbl.add ctx.namespace_table ns h;
+    Hashtbl.add ctx.namespace_table ns (Internal h);
```
and
```
-      (try Thash (Hashtbl.find ctx.namespace_table name)
+      (try
+          (match Hashtbl.find ctx.namespace_table name with
+            | Internal t -> Thash t
+            | Custom _ -> Tnull)
```

**Comment by sagotch** [comment]
As frames would now be of type `(string -> tvalue)`, we should keep a function such as

```
let jg_push_frame ctx frame =
  {ctx with frame_stack = frame :: ctx.frame_stack}
```
So we can use it like this:
```
  let ctx = jg_push_frame ctx (function
      | "loop" -> Tpat begin function
        | "index0" -> Tint !i
        | "index" -> Tint (!i + 1)
        | "revindex0" -> Tint (len - !i - 1)
        | "revindex" -> Tint (len - !i)
        | "first" -> Tbool (!i = 0)
        | "last" -> Tbool (!i = len-1)
        | "length" -> Tint len
        | "cycle" -> cycle
        | _ -> raise Not_found
      end
     | _ -> raise Not_found
  ) in
```

instead of creating a Hashtbl with one value only.

**Comment by Chimrod** [comment]
Thanks for your suggestions. I'll try to implement this and keep you informed !

**Comment by tategakibunko** [comment]
Thanks for the commit and review, I finally understood what you guys were trying to do!

So both the models and the frame can be abstracted to `string -> tvalue` internally.

It's certainly more essential than being limited to assoc list or Hashtbl.

Thank you. I learned a lot.

**Comment by Chimrod** [comment]
You'r welcome (-:

Now that the internals changes are done, it is time to open this flexibility to the end users and update the API.

I let you choose how you want to new the new functions in Jingoo.Jg_template

**Comment by roddyyaga** [comment]
Can this functionality available be made available in `Jg_template` and released on opam now? I'm happy to write a PR if there's more stuff that needs to be done.

**Comment by tategakibunko** [comment]
Currently, the policy is to create new functions in parallel with the existing API.

The name and design of the new function is under consideration by Chimrod, but we will discuss it again when we have a PR.

Of course I will release it to opam as soon as it's implemented, but any new PRs are welcome.

**Comment by tategakibunko** [comment]
@Chimrod @roddyyaga 

Maybe I misunderstood the conversation.

> I let you choose how you want to new the new functions in Jingoo.Jg_template

I thought I had a choice to make about the results you implemented.

Did you mean to say that the implementation was delegated to me?

If so, I didn't do anything in particular...I apologize for my poor English reading comprehension.

If @roddyyaga has some implementation about this functionality, I will gladly merge the implementation.

**Comment by tategakibunko** [comment]
So I've pushed draft api for this Issue.

https://github.com/tategakibunko/jingoo/commit/b3327a21cc4ab7d4207aedbc6d6e5da2fcf99d11

Feel free to review this commit!

**Comment by sagotch** [comment]
I did not really reviewed, but just a quick question: what the `_ex` stand for?

It makes me think about the `_exn` function variation you can often find in OCaml code for functions raising an exception.

**Comment by tategakibunko** [comment]
> what the _ex stand for?

That's the name as a draft. I couldn't think of a good name for now.

If someone recommends another good name, I'll fix it.

**Comment by roddyyaga** [comment]
Looks great! Maybe the new functions could be put in a module in `Jg_template` called `Fun_model`/``Model_getter` or similar? Also, can the corresponding functions be added to `Jg_template.Loaded` as well?

**Comment by tategakibunko** [comment]
> Also, can the corresponding functions be added toJg_template.Loaded` as well?

Oh, I forgot about it... I'll add it later(as `Jg_template.Loaded.eval_ex`).

Thanks for the review!

**Comment by tategakibunko** [comment]
I've added `Jg_template.Loaded.eval_ex`.

https://github.com/tategakibunko/jingoo/commit/0fbcf8b4de9286fd67b1452662acd6c748bbd220

But the name `***_ex` might be confusing for devs, so it's a draft.

If you have a better name, please feel free to let us know.

**Comment by roddyyaga** [comment]
Maybe `***_model_fun` or something similar indicating that the models are specified with a function rather than a list?

**Comment by sagotch** [comment]
> `_fn` would be short enough and descriptive enough for me.

**Comment by tategakibunko** [comment]
`from_string_model_fun` is friendly but it feels a little redundant.

`from_string_fn` is descriptive than `_ex` but it feels like a function that returns a function for me.

Would it be confusing if we gave it a completely different name as a reviced version of old api? For example

`output_from_string`, `output_from_file`, `output_from_chan`

**Comment by roddyyaga** [comment]
I think it would be a bit confusing if it had a significantly different name that wasn't related to the new model parameter. Rather than `function` possibly something based on `getter` or `lookup` might work? Or alternatively could just do `from_string'` etc.

**Comment by tategakibunko** [comment]
Hmm, `from_string'` or same function name in another sub module(like `Jg_template2.from_string` or `Jg_template.XXX.from_string`) seems good idea!

Because I've seen similar solution in `ocamlnet` library.

If we have reviced api in submodule, what is the best name for it?

**Comment by sagotch** [comment]
I like the submodule idea :+1:

**Comment by tategakibunko** [comment]
I like this idea too!

Then which do you like prefer `Jg_template2.from_string` or `Jg_template.XXX.from_string`?

**Comment by tategakibunko** [comment]
TBH, I prefer `Jg_template2`	for some reason, because `Jg_template` module includes `Loaded` module.

If we goto `Jg_template.XXX.from_string`, then we shold also create `Jg_template.XXX.Loaded.eval`,	nesting level is a bit deep.

If we create Jg_template2, then we have

- `Jg_template.from_string`, `Jg_template.Loaded.eval`
- `Jg_template2.from_string`, `Jg_template2.Loaded.eval`

seems simple and clean.

**Comment by sagotch** [comment]
I agree, submodule could be quite long. `Jg_template2` is good for me.

**Comment by tategakibunko** [comment]
Thank you for your feedback!

Then I'll implement `jg_template2`.

**Comment by tategakibunko** [comment]
I've pushed `Jg_template2`.

https://github.com/tategakibunko/jingoo/commit/9bc52fedc35522d3f45ed0a71982db4a40f26082

If it seems ok, then I'll close this issue and release new version to opam.

**Comment by Chimrod** [comment]
Thank you (sorry I have been away for a long time) !
