### ISSUE TITLE
Use symbolic HTML entities rather than character codes for escaping

### ISSUE THREAD

**Issue by dmbaturin** [tategakibunko/jingoo#116]
Right now the `escape` function uses numeric ASCII codes like `&#62;`. This if functional, but can be hard for a human reading that HTML. It's also a bit contrary to the way many other tools work. Symbolic entities like `&gt;` are easier to read.

However, I did look in the code and I see why you went with numeric codes—since all required codes consist of two digits, the length of the substitute substring is constant: one character like `>` is always replaced by a 5-character string like `&#62;`. A variable-length implementation is more annoying to make.

If you aren't categorically opposed to a variable-length implementation, I'm ready to help with it. Just want to check first.

**Comment by tategakibunko** [comment]
Current implementation of `escape_html` is quite performant but at the same time, I agree with your frustration, it's not easy to read.

So feel free to send us your PR!

**Comment by tategakibunko** [comment]
I've updated `escape_html`(character number -> character reference).

https://github.com/tategakibunko/jingoo/commit/c4411fa66c87539076dc9b74c35d8ad0a6c2af6d

It will be included in next release.

Thanks for raising the issue!

**Comment by dmbaturin** [comment]
Thanks!
I've been busy fighting with the calendar library and you got ahead of me. I like your implementation.

When do you plan to make a new release?

**Comment by tategakibunko** [comment]
We'll probably release it in the near future (this month).

**Comment by dmbaturin** [comment]
Great! I'm planning to make a new soupault release late in this month, too.
