### ISSUE TITLE
No way to set models in built-in executable

### ISSUE THREAD

**Issue by Lysxia** [tategakibunko/jingoo#128]
Unless I'm missing something, in `jg_cmdline.ml`, `let models = ref []` is never written to:

https://github.com/tategakibunko/jingoo/blob/cd4b6f29c3b9c00ee28cf3b9917eb95dbea2440c/src/jg_cmdline.ml#L16

**Comment by tategakibunko** [comment]
Currently, giving models from the command line is not implemented.

If you want to use `jg_cmdline` to give the model variable, you can use the `set` command at the top of the template file.

```jinja2
{% set list = ["foo", "bar", "baz"] %}

{% for item in list %}
  {{ item }}
{% endfor %}
```

**Comment by Lysxia** [comment]
Thanks, that solution is good enough for me!
