### ISSUE TITLE
May I ask how to do list appending on version 1.2.21 

### ISSUE THREAD

**Issue by funnycrab** [tategakibunko/jingoo#129]
Hello, thanks for creating this fantastic project!

Just I am having trouble to append item into list in template. For some reason I am using version **1.2.21**(and probably have to stay with it for some time). Basically, below code does not work,
`{% set a = [] %}
{{ a.append("a") }}
{{ a | length }}

OUTPUT of above code: 0
`
Is this normal/expected?

I see there is an addition of overload of jg_plus to support list operation in v1.3.0, would upgrade to 1.3.0 solves my issue?

Thanks a lot in advance!

**Comment by sagotch** [comment]
Hi.

Can you use this?

```jingoo
{% set a = [] %}
{% set a += ["a"] %}
{{ a | length }}
```

**Comment by sagotch** [comment]
Another option if you really need to stick with older version is to use the `filters` field of https://github.com/tategakibunko/jingoo/blob/36ea1dcac8516498c6a0db64eda9ff53b021cbc8/src/jg_types.mli#L11 in order to create (or copy as) your own `append` filter.

**Comment by funnycrab** [comment]
Thanks for the quick reply @sagotch !

I think in this case, I would probably try to get a new version which seems easier.

Feel free to consider this issue has been resolved.
