### ISSUE TITLE
Is there a way to pass data into template

### ISSUE THREAD

**Issue by funnycrab** [tategakibunko/jingoo#130]
In Jinja, it is possible to pass data to template via some function calls. May I know if similar thing can be done in Jingoo?

Thanks in advance!

**Comment by sagotch** [comment]
Could you provide an example for the jinja version? I do not understand what you are asking for.

**Comment by funnycrab** [comment]
Hello again sagotch,

Sorry for not being clear, basically what I mean is, if I were using Jinja + python, then I can write something like following to pass data from python code to template,

```python
#!/usr/bin/python3

from flask import Flask, render_template

app = Flask(__name__)


@app.route("/tuple")
def jpg_to_pdf():
    results = [(1, 'Dummy1', 'dummy1', 1), (2, 'Dummy2', 'dummy2', 2), (3, 'Dummy3', 'dummy3', 3)]
    return render_template('index.html', data=results)
```

and in template, I can refer to data being passed in by variable name "data", i.e.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tuple</title>
</head>
<body>
<table style="width: 100%">
{% for element in data %}
 <tr>
    <th>{{ element[0] }}</th>
    <th>{{ element[1] }}</th>
    <th>{{ element[2] }}</th>
    <th>{{ element[3] }}</th>
  </tr>
{% endfor %}
</table>
</body>
</html>
```

So I am just wondering, if I can do something similar with Jingoo + Ocaml(of course)?

I've searched through the repo and I feel that something like "render_template" does not exist in Jingoo.
(To be fair, the `render_template` function in the example is not from Jinja either, it is from flask. But I am just wondering if anything similar can be found in Ocaml world.)

**Comment by tategakibunko** [comment]
Maybe `Jg_template.from_file` is what you want.

https://github.com/tategakibunko/jingoo#ocaml-code.
