### ISSUE TITLE
urlencode filter

### ISSUE THREAD

**Issue by reynir** [tategakibunko/jingoo#131]
It could be useful to have the [`urlencode`](https://jinja.palletsprojects.com/en/3.1.x/templates/#jinja-filters.urlencode) filter

**Comment by tategakibunko** [comment]
I've implemented urlencode filter only for strings and iterables, but is it required for mapping data?
https://github.com/tategakibunko/jingoo/pull/132

**Comment by reynir** [comment]
For me it is fine with strings only :-) Thank you!
