### ISSUE TITLE
Lazyness / Functor

### ISSUE THREAD

**Issue by sagotch** [tategakibunko/jingoo#30]
Hey !

First, thank you for your work, I was very glad to find a jinja parser/interpreter for OCaml.

I started a lot of modifications (you already saw some of my PR). Another thing that I have done is to implement lazyness for `tvalue`. I did it with a new `Tlazy of tvalue Lazy.t` constructor. It is very useful (and even mandatory) for recursive data structure without wrapping everything in functions (i.e. a `person` has a `mother`, which is a `person` herself).

Also, I plan (but I do not know when) to functorize `jingoo` in order to allow the user to use a custom type `'a value = ... | Taplha of 'a`.

My question is : are you interested in having a `Tlazy` constructor? If not, are you interested in having `jingoo` as a functor (with default values, like`Hashtbl` module). If you are not interested in laziness but you are interested in functor, I could implement the lazyness as a custome type so it would be okay for me. If none of these option suit you, well... I guess that it would be ok to keep my fork up to date with your repo...

**Comment by tategakibunko** [comment]
Thanks for your proposal!
Both recursive data structure(lazy feature) and user extendable feature(Functor) looks fine to me if all patch works fine with backward compatibility.

**Comment by sagotch** [comment]
It does/will.

Il will make a PR for lazyness today, and I hope to make another PR for functor in a near future, but I have no time to work on it right now.

**Comment by sagotch** [comment]
As I get my answer, I am closing this one.
