### ISSUE TITLE
Custom string_of_tvalue for objects

### ISSUE THREAD

**Issue by sagotch** [tategakibunko/jingoo#38]
I think that original jinja engine would render an object using its `__str__` method. I would like to have the same behavior in jingoo. If `string_of_tvalue` is called on an object, I would expect it to look for a `__str__` (or another name, but I would prefer to stick with the original conventions).

Would you accept a PR to make `string_of_tvalue` looks for this property and uses `"<obj>"` (or corresponding strings) if the property is not found.

**Comment by tategakibunko** [comment]
I also think difference between jinja2 and jingoo should be small.

So if you can send PR about this issue, it's welcome!
