### ISSUE TITLE
Extends from string

### ISSUE THREAD

**Issue by pdonadeo** [tategakibunko/jingoo#42]
I have a usage question: is it possible to extend a string template (`Jg_template.from_string`) from another string template?

I'm in the situation in which templates should not be distribuited and I'm keeping those in memory, as OCaml strings.

**Comment by tategakibunko** [comment]
Currently the answer is NO.

But I'll support `extends from` syntax in next release.

```jinja2
Jg_template.from_string @@ String.concat "\n" [
  "{% extends from '<main>{% block main %}{% endblock %}</main>' %}";
  "{% block main %} this is main {% endblock %}";
]
```

... Is this	what you want?

**Comment by pdonadeo** [comment]
Thanks for your reply! That is not exactly what I mean. I have a template from a string:
```ocaml
  let child = Jg_template.from_string @@ String.concat "\n" [
    "{% extends \"parent.html\" %}";
    "{% block main %}child{% endblock %}";
  ]
```
where `parent.html` is not an actual file but another template, defined before `child`:
```ocaml
  let parent = Jg_template.from_string "{% block main %}main{% endblock %}"
```
In Jinja2 a "loader" machinery is available: http://jinja.pocoo.org/docs/2.10/api/#loaders

In [Django](https://www.djangoproject.com/) I usually store templates in PostgreSQL because you have the chance to load them from virtually anywhere.

**Comment by tategakibunko** [comment]
Oh...then, the answer is NO.

Jingoo has no loader like jinja2.

**Comment by pdonadeo** [comment]
@tategakibunko ok thanks, it's fair. Maybe in the future I could contribute with a patch.

I'm closing this not-an-issue :)
