### ISSUE TITLE
File extension

### ISSUE THREAD

**Issue by sagotch** [tategakibunko/jingoo#51]
For each template language, there is the same debate if no extension is mentioned by the creator, so I would suggest to pick `.jingoo` (or anything you like) and mention it in the doc as a *not-mandatory-but-preferred* file extension. It is a common practice to use the full name of the markup language as file extension.

For instance, Jinja2 has no official extension, but emacs `jinja2-mode` uses `.jinja2` https://github.com/paradoxxxzero/jinja2-mode/blob/master/jinja2-mode.el#L324

**Comment by tategakibunko** [comment]
`.jingoo` looks simple and good, and it will be SEO friendly too.

**Comment by tategakibunko** [comment]
Renamed default templates in this project from *.tmpl to *.jingoo.

https://github.com/tategakibunko/jingoo/commit/fa401a1d89786f9efb3d89c9b10e9c0eedbe8ca9
