### ISSUE TITLE
Function language extension

### ISSUE THREAD

**Issue by sagotch** [tategakibunko/jingoo#52]
Would you be against a new `function` keyword, which is basically a macro, but returning a `tvalue` instead of something meant to be print?

Something like:

```
{% function aux (str) %}
  {{ (upper (str[0]), str) }}
{% endfunction %}

{% for grouper, list in data | map ("aux") | groupby ("[0]") %}
  <ul>
    {{ grouper }}
    {% for s in list %}<li>{{ s }}</li>{% endfor %}
  </ul>
{% enfor %}
```

**Comment by tategakibunko** [comment]
Hmm, a little question.

Both `grouper` and `list` are iterate item, but are `map("aux")` and `groupby("[0]")` only applied to `list`?

And `(upper(str[0]), str)` returns multi value?

Anyway, we have some way to extends runtime function via
`Jg_types.environment.extensions`( `advanced.ml` and `my_ext.ml` in example directory).

I think `map` in template looks interesting, but at the same time, function via `Tstr fun_name` is too powerful and a little bit confusing.

**Comment by sagotch** [comment]
> And (upper(str[0]), str) returns multi value?
It is a set, isn't it? Maybe it should be written `[ upper(str[0]), str ]`, I did not check the set syntax.

> Both grouper and list are iterate item, but are map("aux") and groupby("[0]") only applied to list?
filters are applied to `data`

`map` is a built-in jinja filter (http://jinja.pocoo.org/docs/2.10/templates/#map), and I already added it (but not tested yet, that is why there no PR for now) as part of the standard filters.
I agree that function via `Tstr` is strange, I actually picked this because it is what is done in jinja, even if I do not like it (at all).

I do not understand this choice, and I would prefer `map` with value instead of string.
I would say that it is okay to treat both `string` and `value` cases, in order to be compatible with jinja2, but also to allow people to do things right. Otherwise, only allowing values is okay for me.

### For the `function` thing...

`function` is a way to build filter without ocaml code. My concern is that my templates are for people who do not want to write ocaml. OCaml is not even installed on their machines.

I guess that only anonymous function would suit my needs as well, but it also extends the language.

```
{% for grouper, list in data | map ((str) ->  (upper (str[0]), str)) | groupby ("[0]") %}
  <ul>
    {{ grouper }}
    {% for s in list %}<li>{{ s }}</li>{% endfor %}
  </ul>
{% enfor %}
```
It may lack some code reusabillity at some point, but I do not really mind for now.

Also, in order to apply filter with multiple argument, you could also combine `function` and anonymous function system like this.

```
{% function aux (str, trailer) %}
  {{ (upper (str[0]), str + trailer) }}
{% endfunction %}

{% for grouper, list in data | map ((str) -> aux (str, "!")) | groupby ("[0]") %}
  <ul>
    {{ grouper }}
    {% for s in list %}<li>{{ s }}</li>{% endfor %}
  </ul>
{% enfor %}
```

Maybe it is too powerfull indeed, so what I will do for now is write a custom filter like the `eval` one in order to allow

```
{% for grouper, list in data | map (fun ("(str) ->  (upper (str[0]), str)")) | groupby ("[0]") %}
  <ul>
    {{ grouper }}
    {% for s in list %}<li>{{ s }}</li>{% endfor %}
  </ul>
{% enfor %}
```
It means that I need parsing at runtime, but this part could be fixed with `jg_ast_mapper` which would prepare the env and avoid this.

I will forget this `function` extension for now, because my problem can easily be solved with a filter, but this kind of question is something that often shows up while dealing with templating system. (with pro and cons, and the question of separation of logic/rendering)

**Comment by tategakibunko** [comment]
>filters are applied to data

Ohh, filter is applied to `data`, so right associative, I get it!

>function is a way to build filter without ocaml code. My concern is that my templates are for people who do not want to write ocaml. OCaml is not even installed on their machines.

That makes total sense, surely it will be helpfull for some users.

There is some environment that can't use native compiler, then they can't use *.cmx, so this feature will be helpfull for them too.

So I agree with this `function` feature!

**Comment by sagotch** [comment]
FYI, I do not plan to support this anymore. While it *may* be useful to have functions able to return objects or numbers, my use case will only need strings.

`eval` filter is perfectly suited for this, so I could get the output of a macro with `{{ eval ('{{ long_married(f, xx) }}') | capitalize }}`.

May be when I will need it again ;-)
