### ISSUE TITLE
Release trouble about jingoo 1.3.0

### ISSUE THREAD

**Issue by tategakibunko** [tategakibunko/jingoo#79]
I've try to release `jingoo 1.3.0` today, but it failed...

Maintainer is guessing that "the repository revision it was made from doesn't contain all the dependencies of the package".

https://github.com/ocaml/opam-repository/pull/13422#issuecomment-461749066

@sagotch  I have no idea about this, do you know anything about this?

**Comment by AltGr** [comment]
This could probably be solved by running, from your clone or `ocaml/opam-repository`:
```
git remote add ocaml git@github.com:ocaml/opam-repository
git fetch ocaml
git rebase ocaml/master
git push
```

That should be enough to update your branch to the upstream repository, and update the corresponding pull-request.

**Comment by tategakibunko** [comment]
It's merged!! Thank you very much!!
