### ISSUE TITLE
{% switch %} statement

### ISSUE THREAD

**Issue by sagotch** [tategakibunko/jingoo#80]
Pattern matching would be really useful in order to avoid long series of `{% if foo == ... %}` with foo being the same in each `elif` case. I plan to add a `switch` statement to jingoo.

```
{% switch foo.bar %}
  {% case "foo" %}{{ 1 }}
  {% case "bar" %}{{ 2 }}
  {% case baz case toto %}{{ 3 }}
  {% default %}{{ -1 }}
{% endswitch %}
```

Also, it would be a more efficient way to compare values (if the value to compare needs some calculation for instead, you would need to use a `set` or every `elif` would be a waste of ressources.)

Any idea/objection?

EDIT:
```
{% case baz case toto %}
```
Would be a problem for the parser if you want to allow 'no statements' as right hand part of the case
```
{% switch foo.bar %}
  {% case "foo" %}
  {% case "bar" %}{{ 2 }}
{% endswitch %}
```
Would be the same as
```
{% switch foo.bar %}
  {% case "foo" case "bar" %}{{ 2 }}
{% endswitch %}
```
Which is obviously not what is wanted.

**Comment by tategakibunko** [comment]
Hmm, in my rough understanding, statement structure will be like bellow?

```ocaml
SwitchStatement of expr * (tvalue, ast) list * ast option
```

and if switch case is like

```c
switch(expr){
  case "foo":
  case "bar": ast1
  case 100: ast2
  default: ast3
}
```

it becomes

```ocaml
SwitchStatement(
  expr, [
    (Tstr "foo", ast1); (* case label "foo" *)
    (Tstr "bar", ast1); (* case label "bar" *)
    (Tint 100, ast2);   (* case label 100 *)
], Some ast3) (* default *)
```

then `expr` is evaluated only once(unlike if else statement), and matched case is searched by

```ocaml
let value = value_of_expr env ctx expr in
if jg_eq_eq value (Tstr "foo") then ast1
else if jg_eq_eq value (Tint 100) then ast2
else match ast3 with Some ast3 -> ast3 | None -> []
```

Both expr value and label value of case are tvalue, then we can compare them by using `jg_eq_eq`.

Is it the "pattern matching" you said?

**Comment by sagotch** [comment]
See https://github.com/geneanet/jingoo/commit/1d220adb6146c104dda247415cec69dca0a57b7a for a first draft. It does not handle multiple `case` evaluating to same value yet.

**Comment by tategakibunko** [comment]
Thanks for reference, I've read it, compact and beautiful implementation!

**Comment by sagotch** [comment]
With https://github.com/geneanet/jingoo/commit/c026c28d4625d30b9f0f278fe3223446a84aceb7

You can use `{% case foo || bar || baz %}`. What do you think about this syntax?

**Comment by tategakibunko** [comment]
After reading code, I can understand the meaning easily, but in first look, `foo || bar || baz` part seems like boolean value?

```
if ((foo || bar || baz) === true){ ... }
```

But it's my own feeling...

**Comment by sagotch** [comment]
I should have write
```
{% switch x %}
  {% case "foo" || "bar" || "baz" %}{{ ... }}
  {% default %} {{ ... }}
{% endswitch %}
```

**Comment by tategakibunko** [comment]
Are case values allowed for direct value only?

In current impl, it seems it can be variable.

**Comment by tategakibunko** [comment]
But if it's only allowed for direct values,  `{% case "foo" || "bar" || "baz" %}` seems short and good syntax.

**Comment by sagotch** [comment]
I am actually using it with variable in my code.

```
{%- set T_ROOT = 0 -%}
...
{%- set T_WITNESS = 7 -%}
{%- set T_GODPARENT = 8 -%}

...

  {%- switch r -%}
    {% case T_ROOT || T_WITNESS || T_GODPARENT %}{{ ... }}
    {%- default -%}{{... }}
  {%- endswitch -%}
```

Would you say that `{% case "foo" case "bar" case "baz" %}` would be a better/good choice. Or something else?

**Comment by tategakibunko** [comment]
What I worry about is confliction like this,

```jingoo
{% set a = false %}
{% set b = true %}
{% set c = false %}

{# good! #}
{% case a || b || c %} {{ ast }} -> Case([a,b,c], {{ ast }})

{# oops! #}
{% case a || b || c %} {{ ast }} -> {% case (a || b || c) %}{{ast}} -> Case([b], {{ast}})
```

If this kind of reducing never happen, I'm ok, but I've not read all current parser yet, so I can't judge.

**Comment by sagotch** [comment]
What happens here is that it is parsed as:
```
{% case a || b || c %} {{ ast }} -> {% case (a || b || c) %}{{ast}} -> Case([b], {{ast}})
```
But parsed output is post-processed:
```
    let rec extract = function
      | OrOpExpr (e1, e2) -> extract e1 @ extract e2
      | e -> [e] in
    SwitchStatement ( e
                    , List.fold_right
                        (fun (a, b) acc -> ([a], b) :: acc) (cases)
                        (match default with None -> [] | Some stmts -> [ ([], stmts) ]))
```

**Comment by tategakibunko** [comment]
Thanks for reply. `OrOpExpr` is not evaluated before building `SwitchStatement`, and always generates list by `extract`, then I'm OK.

**Comment by tategakibunko** [comment]
Apparently `{% case "a" %}{% case "b" %}` or `{% case "a" case "b" %}` thing is hard to type, I agree with you.
