### ISSUE TITLE
Truncated function expansion

### ISSUE THREAD

**Issue by paurkedal** [tategakibunko/jingoo#84]
When `{{ ... }}` occurs inside a function body, only the last piece of the function body is returned, whether it is a literal part or an substituted value:
```ocaml
utop # #require "jingoo";;
utop # open Jingoo
utop # Jg_template.from_string "{% function test() %}a{{x}}{% endfunction %}{% set x = 'b' %}{{test()}}";;
- : string = "b"
utop # Jg_template.from_string "{% function test() %}a{{x}}c{% endfunction %}{% set x = 'b' %}{{test()}}";;
- : string = "c"
```

**Comment by tategakibunko** [comment]
Thank you for reporting!

Please use `macro` instead of `function` until we fix this issue, it works.

```ocaml
utop # Jg_template.from_string "{% macro test() %}a{{x}}{% endmacro %}{% set x = 'b' %}{{ test() }}";;
- : string = "ab"
utop # Jg_template.from_string "{% macro test() %}a{{x}}c{% endmacro %}{% set x = 'b' %}{{ test() }}";;
- : string = "abc"
```

**Comment by paurkedal** [comment]
I was citing the minimal code to demonstrate the issue.  For my actual use, I filter the function body before emitting it, my actual expansion looks like
```jinja2
(* {{ license_header() | replace('\n', '\n * ') }} *)
```
If there is a way to filter a `rawinclude`, that would work too.  I tried `{{ rawinclude("some-file") | replace('\n', '\n * ') }}`, but the filter is silently ignored.

In any case I find the semantics of only returning the last evaluated piece counter-intuitive and I am wondering what use the former pieces play?  If it is not supported, should multi-piece function bodies not be rejected?  I think it would be less useful than allowing it, but at least one could catch errors where one forgets the `-` before `endfunction` in an example like:
```jinja2
{% function inv (reverse=false, x, y) -%}
  {%- if reverse %}{{ {a:y,b:x} }}{% else %}{{ {a:x,b:y} }}{% endif -%}
{%- endfunction -%}
```

**Comment by tategakibunko** [comment]
The purpose of `function` is to write custom filter in template code, not to output whole body as string like `macro`.

So if you want to output all parts of code-body as string, it's the task of `macro`, not `function`.

I think it's natural for `function` returns the last pieces of body, suppose you write **function** like this...

```ocaml
let foo x y =
  print_endline x;
  print_endline y;
  x ^ y
```

Then apparrently all you want from `foo` is only `x ^ y`(string) isn't it?

That aside, `rawinclude` is syntax statement(like `for`, `if`), it's not expression, so filter doen't work.

But you can create some **navive** custom filter in ocaml like bellow.

```ocaml
let string_of_file path	=
  Tstr (Jg_utils.read_file_as_string path)

let my_env = {std_env with 
  filters = [("string_of_file", Jg_type.func_arg1 string_of_file)]
}

Jg_template.from_string	~env:my_env "{{ string_of_file("some-file") | replace('\n', '\n * ') }}"
```

About custom filter, see https://github.com/tategakibunko/jingoo/blob/master/README.md#custom-filter-example

**Comment by paurkedal** [comment]
Okay, I see one can make sense of the function-semantics by analogy to OCaml statements.  I think there is an important difference though.  In case of ocaml `"a"; x; "b"` would give warnings about the first two statements returning non-unit.  So, following that line, I think more useful semantics for the function body would be to only accept non-content pieces (like `{% set ... %}`) before the value to be returned.  For convenience one could also strip all whitespace (analogously to `<xsl:strip-space .../>`).

I'll probably use a custom filter, as you suggest then, or maybe resorting to my original though of using a macro with `{{ line_prefix }}` on each line, though the latter gets rather verbose and hard to reindent.

I like very much having a template language so close to Jinja2, but I also wish the strict mode was a lot stricter.  Another issue I had is reporting undefined variables.  At the moment I have to inspect the result carefully to be sure nothing is missing or mis-rendered.  Would further constraints on the strict mode be a reasonable direction if I were to open new issues or PRs?  (I don't have time for a PR right now, but maybe later.)

**Comment by tategakibunko** [comment]
>  I also wish the strict mode was a lot stricter.

Yes, `strict mode` was added recently and still immature.

So if you have some idea and send us PR, it's welcome!

**Comment by sagotch** [comment]
Sorry for resurrecting an old thread, but I probably missed it by the time it was written.

> Okay, I see one can make sense of the function-semantics by analogy to OCaml statements. I think there is an important difference though. In case of ocaml `"a"; x; "b"` would give warnings about the first two statements returning non-unit. So, following that line, I think more useful semantics for the function body would be to only accept non-content pieces (like `{% set ... %}`) before the value to be returned.

`{{ side_effect_function () }}` would be forbidden then.

>  For convenience one could also strip all whitespace (analogously to `<xsl:strip-space .../>`).

That is what `{%-` does. I agree it is a source of errors, but I would prefer some kind of linter to statically analyses your template that would warn you about possible mistakes than an automatic trimming,

**Comment by paurkedal** [comment]
> `{{ side_effect_function () }}` would be forbidden then.

Yes, but is it not better to use a macro if no value is returned?  Then `{{ side_effect_macro () }}` still be allowed?  Is a function needed in cases where no value is returned?

> > For convenience one could also strip all whitespace (analogously to `<xsl:strip-space .../>`).
> 
> That is what `{%-` does. I agree it is a source of errors, but I would prefer some kind of linter to statically analyses your template that would warn you about possible mistakes than an automatic trimming,

Yes, if it's checked, one can idiomatically use `{%-` and `-%}` consistently in function bodies and on the inwards-facing brackets of the function definition itself.

**Comment by sagotch** [comment]
> Yes, but is it not better to use a macro if no value is returned? That is, `{{ side_effect_macro () }}` could be allowed, as long as `side_effect_macro` is a macro?

You will eventually find a case when you wish functions not to be that restrictive. What I said for automatic trimming can also apply here. I prefer that a linter warn we about potential mistake. You can write a checker for functions quite easily with ast mapper and run it before you render your template to warn about error or to automatically correct it.

This kind of tool is on my long-term todo (not actually on any list, so I should say very-long-term todo list).

**Comment by paurkedal** [comment]
My reasoning is that, assuming the only difference between macros and functions is whether a value is returned, a function not returning a value is better written as a macro and a function returning a value is not performing it's task unless it's in the last-fragment position.  But there may be corner cases where one wants the effect without the value, like when one would use `ignore` in OCaml code.

Anyway, I don't expect anyone to work on this.  I originally though I hit a bug, but that was due to a misunderstanding of the semantics (which I though was more pure, like xslt).
