### ISSUE TITLE
Proposal: += operator

### ISSUE THREAD

**Issue by sagotch** [tategakibunko/jingoo#91]
I sometime use a lot of `{% set %}` instructions in my templates in order to conditionally concatenate string in functions. Supporting `+=` operator for affectations would simplify a little bit their writing.

```jinja2
{% set res = res + 'foo' %}
{% set res += 'foo' %}
```

Would it worth it to add this feature?

**Comment by tategakibunko** [comment]
Sounds good! 

There is no reason to oppose. Clearly`+=` is better.
