### ISSUE TITLE
else if

### ISSUE THREAD

**Issue by sagotch** [tategakibunko/jingoo#92]
A mistake I do quite often is to use `{% else if ... %}` instead of `elif` or `elseif`. Would you mind supporting `else if` as well? Of course, I can propose a PR for this if you agree.

**Comment by tategakibunko** [comment]
> A mistake I do quite often is to use {% else if ... %}

Haha, me too! (even if in `jinja2`)

If we can support `else if`, it will be great(although compatibility between jinja2 and jingoo is worse than it is now...)
